# copy vs view

In [7]:
import numpy as np
var = np.array([1,2,3,4])

co = var.copy()
var[1] = 40
print(var)
print(co)

[ 1 40  3  4]
[1 2 3 4]


In [6]:
x = np.array([9,8,7,6,5])
x[1] = 40
co1 = x.view()
print(x)
print(co1)

[ 9 40  7  6  5]
[ 9 40  7  6  5]


# join arrays

In [9]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([9,8,7,6])
ar = np.concatenate((a,b))
print(ar)

[1 2 3 4 9 8 7 6]


In [13]:
import numpy as np
a1 = np.array([[1,2],[3,4]])
b1 = np.array([[9,8],[7,6]])
ar1 = np.concatenate((a1,b1),axis=1)
ar2 = np.concatenate((a1,b1),axis=0)
print(ar1)
print(ar2)

[[1 2 9 8]
 [3 4 7 6]]
[[1 2]
 [3 4]
 [9 8]
 [7 6]]


In [17]:
a2 = np.array([1,2,3,4])
b2 = np.array([9,8,7,6])
ar3 = np.stack((a2,b2),axis=1)
arh = np.hstack((a2,b2))  #row
arv =  np.vstack((a2,b2)) #columns
arvv = np.dstack((a2,b2))  #height
print(arh)
print()
print(arv)
print()
print(arvv)

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


# split

In [21]:
import numpy as np
p = np.array([1,2,3,4,5,6])
new = np.array_split(p,3)
print(new)
print(new[0])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]


we can use the array_split funtion to split the array into our desired number of parts by specifying the no of parts in the array_ssplit function

In [22]:
p1 = ([[1,2],[3,4],[5,6]])

new = np.array_split(p1,3)
print(new)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


# search

import numpy as np
q = np.array([1,2,3,4,2,5,6,7])

s = np.where((q == 2))
s1 = np.where((q%2) == 0)
print(s)
print()
print(s1)



.where funtion is used in numpy to finad an element in the array and fetch there indexes
and it can also be used to find out elemnts in the array with specific conditions

In [25]:
q1 = np.array([1,2,3,4,6,7])

s2 = np.searchsorted(q1,5)
print(s2)

4


searchsorted function is used in numpy tp find the where we can place a variable in a sorted array at the correct position

# sort

In [26]:
import numpy as np
q2 = ([8,74,2,15,6,78,655])
print(np.sort(q2))

[  2   6   8  15  74  78 655]


In [27]:
q3 = (["a","z","s","b","q"])
print(np.sort(q3))

['a' 'b' 'q' 's' 'z']


sort function can be used in numpy to sort an unsorted array

# filter array

In [31]:
import numpy as np
r = np.array(["a","z","s","b","q"])
f = [True,False,False,True,True]
new = r[f]
print(new)




['a' 'b' 'q']


In [33]:
r1 = np.array([8,74,2,15,6,78,655])
f1 = [True,False,False,True,True,False,True]
new1 = r1[f1]
print(new1)


[  8  15   6 655]
