# arithmetic operations

In [17]:
import numpy as np

var = np.array([1,2,3,4,5,32,])

print(np.min(var))
print(np.max(var))
print(np.argmin(var))
print(np.argmax(var))
print(np.sqrt(var))


1
32
0
5
[1.         1.41421356 1.73205081 2.         2.23606798 5.65685425]


the min and max functions are used in numpy to find the biggest and smallest number in the array respetively, and argmin and argmax functions are used to mark the position(address) of the smallest and biggest number in the array respetively. the sqrt function is used to find the square root of each element in the array


sin and cos funtion can be used to find sine and coisne value of the elements

In [16]:
import numpy as np

var1 = np.array([[2,1,3],[9,5,6]])
print(np.min(var1, axis = 1))
print(np.min(var1, axis = 0))

[1 5]
[2 1 3]


in a 2d array the argmin function is used to find the min and max numbers in the 2d array
by passing 2 arguments in the function (the variable name , the axis (axis=0 is referred to as column and axis=1 is referred to as row ))

In [18]:
import numpy as np

var3 = np.array([1,2,3,4,5,32,])
print(np.cumsum(var3))

[ 1  3  6 10 15 47]


cumsum is a function in which the 1st element is printed as it is then that element is added to the 2nd element and the result is added is added to the next element and the process continues


# Shape and reshape

In [32]:
import numpy as np
x = np.array([[1,3],[1,2]])
y = np.array([[1,2,3],[1,2,3]])

print()
print(x.shape)
print()
print(y.shape)


(2, 2)

(2, 3)


the shape function in numpy is used to show the number of rows and columns when the array is changed to mathematical matirx form

In [33]:
z = np.array([1,2,3,4],ndmin = 4)
print(z)
print(z.shape)

[[[[1 2 3 4]]]]
(1, 1, 1, 4)


# reshape

In [47]:
x1 = np.array([1,2,3,4,5,6])
print(x1,"dimesnions is:",x1.ndim)

new = x1.reshape(3,2)
print()
print(new)
print(new.ndim)

[1 2 3 4 5 6] dimesnions is: 1

[[1 2]
 [3 4]
 [5 6]]
2


Reshape is  the function that can be used to arrange a set of array according to your specified number of row and columns in the format (reshape(row,column)). 

the shape of the array should be according to the number of elemnts in the array otherwise it will throw a eror

In [10]:
import numpy as np
x2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x2,"dimesnions is:",x2.ndim)

new1 = x2.reshape(2,2,3)
print()
new2 = x2.reshape(2,3,2)

print(new1)
print()
print(new2)
print()
old = new1.reshape(-1)
print(old)



[ 1  2  3  4  5  6  7  8  9 10 11 12] dimesnions is: 1

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


we can convert a 1d array to any specified dimesion array with the help of reshape function and then convert it back to 1d array with the help of passing -1 in the reshape argument

# BROADCASTING

In [15]:
import numpy as np
p = np.array([1,2,3])
print(p.shape)
q = np.array([[1],[2],[3]])
print(q.shape)
print()
print(p+q)
print()
print((p+q).shape)




(3,)
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]

(3, 3)


broadcasting means the priting the output of operations performed to the given arrays

there are some rules for broadcasting like both the arrays while giving their sum should have the same number of elements 

if the dimesnion of the array are different then the shapes of the arrays should have atleast one value in common and the max number of both the shapes will decide the shape of the rrsulting array

NOTES IN COPY ALSO

In [20]:
p1 = np.array([[1],[2]])
print(p1.shape)
q1 = np.array([[1,2,3],[1,2,3]])
print(q2.shape)
print()
print(p1+q1)

(2, 1)
(3, 1)

[[2 3 4]
 [3 4 5]]


# INDEXING AND SLICING

In [25]:
import numpy as np
a = np.array([9,8,7,6])

print(a[1],a[0])
print(a[-4])


8 9
9


In [30]:
a1  = np.array([[9,8,7],[4,5,6]])
print(a1[0,0])
print(a1[0,1])
print(a1[1,2])

9
8
6


In [34]:
a2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a3 = np.array([[[1,2],[6,7]]])

print(a2[0,1,0])
print()
print(a3[0,1,1])

3

7


# SLICING

In [43]:
 import numpy as np
b = np.array([1,2,3,4,5,6,7])
             #0,1,2,3,4,5,6,
             #-7,-6,-5,-4,-3,-2,-1
print(b)
print()
print(b[-7])
print()
print("2 to 5: ",b[1:4])
print()
print(b[1:5:2])
print(b[1:-1])

[1 2 3 4 5 6 7]

1

2 to 5:  [2 3 4]

[2 4]
[2 3 4 5 6]


slicing means taking out varibale from the array and it is done in the format of vriable name (start:stop:step)index

In [52]:
b1 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(b1)
print()
print("9 to 5 :",b1[1,0:4])
print(b1[2,0:-1])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

9 to 5 : [9 8 7 6]
[11 12 13 14]


# ITERATION

nditer is a function that can used to iterate through array of any dimesnions 

In [64]:
d3 = np.array([[[1,2,3],[1,2,3]]])
for i in np.nditer(d3):
    print(i)


1
2
3
1
2
3


iteration in 1d

In [66]:
import numpy as np

d = np.array([9,8,7,6,5,4])
for i in d:
    print(i)

9
8
7
6
5
4


iteration in 2d

In [58]:
d1 = np.array([[1,2,3,4],[5,6,7,8]])
for j in d1:
    print(j)

print()
for k in d1:
    for l in k:
        print(l)

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


iteration in 3d

In [62]:
d2 = np.array([[[1,2,3],[1,2,3]]])
print(d2)
print()
for a in d2:
    print(a)
print()
for b in d2:
    for c in b :
        print(c)

print()
for i in d2:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3]
  [1 2 3]]]

[[1 2 3]
 [1 2 3]]

[1 2 3]
[1 2 3]

1
2
3
1
2
3


In [68]:
d4 = np.array([[[1,2,3],[1,2,3]]])
for i,d in np.ndenumerate(d4):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3


ndenumerate function is used to iterate through the array wih the data and its index